/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        dangen: {
          dark: '#0b000f',
          card: '#14040a',
          red: '#ff003c',
          darkred: '#7a0019',
          accent: '#ff4d6d',
          glow: '#ff1744',
          cyan: '#ff003c',
          purple: '#7a0019',
          green: '#ff4d6d'
        },
        "on-secondary": "#690000",
        "secondary-fixed": "#ffdad4",
        "surface-tint": "#ffb4a8",
        "inverse-on-surface": "#313030",
        "surface-bright": "#3a3939",
        "error-container": "#93000a",
        "inverse-surface": "#e5e2e1",
        "on-surface-variant": "#ebbbb4",
        "primary-fixed-dim": "#ffb4a8",
        "primary-container": "#ff5540",
        "on-secondary-fixed": "#410000",
        "on-tertiary-fixed-variant": "#00530e",
        "tertiary-container": "#00a827",
        "on-tertiary-container": "#003205",
        "outline": "#b18780",
        "surface-container-low": "#1c1b1b",
        "on-background": "#e5e2e1",
        "on-tertiary-fixed": "#002203",
        "secondary": "#ffb4a8",
        "error": "#ffb4ab",
        "secondary-container": "#920703",
        "surface-container": "#201f1f",
        "on-primary-container": "#5c0000",
        "surface": "#131313",
        "on-tertiary": "#003907",
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#920703",
        "on-primary-fixed-variant": "#930100",
        "on-surface": "#e5e2e1",
        "tertiary": "#00e639",
        "on-primary": "#690100",
        "background": "#131313",
        "surface-variant": "#353534",
        "inverse-primary": "#c00100",
        "on-error-container": "#ffdad6",
        "primary": "#ffb4a8",
        "surface-container-lowest": "#0e0e0e",
        "secondary-fixed-dim": "#ffb4a8",
        "surface-container-high": "#2a2a2a",
        "on-secondary-container": "#ff9a8a",
        "tertiary-fixed-dim": "#00e639",
        "outline-variant": "#603e39",
        "surface-dim": "#131313",
        "surface-container-highest": "#353534",
        "tertiary-fixed": "#72ff70",
        "primary-fixed": "#ffdad4",
        "on-primary-fixed": "#410000"
      },
      borderRadius: {
        "DEFAULT": "2px",
        "lg": "4px",
        "xl": "8px",
        "full": "12px"
      },
      spacing: {
        "panel-padding": "20px",
        "base": "4px",
        "stack-lg": "32px",
        "margin-page": "40px",
        "stack-md": "16px",
        "gutter": "24px",
        "stack-sm": "8px"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        display: ['Space Grotesk', 'sans-serif'],
        "headline-lg": ["Sora", 'sans-serif'],
        "label-caps": ["Space Mono", 'monospace'],
        "headline-lg-mobile": ["Sora", 'sans-serif'],
        "body-md": ["JetBrains Mono", 'monospace'],
        "data-point": ["JetBrains Mono", 'monospace'],
        "display-lg": ["Sora", 'sans-serif']
      },
      fontSize: {
        "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "label-caps": ["11px", {"lineHeight": "1", "letterSpacing": "0.15em", "fontWeight": "700"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "body-md": ["14px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "data-point": ["28px", {"lineHeight": "1", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}]
      }
    },
  },
  plugins: [],
}
